import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My first nextjs web",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <a href="/">Home</a>
        </nav>
        <nav>
          <a href="/">Blog</a>
        </nav>
        {children}
      </body>
      <footer>This is footer</footer>
    </html>
  );
};

export default RootLayout;
